/**
 * Mapping of sectors to their constituent stocks
 * Each sector maps to an array of stock symbols that can be fetched from Groww API
 */

export interface SectorStockMapping {
    [sectorName: string]: string[]
}

export const SECTOR_STOCKS: SectorStockMapping = {
    // === BANKING & FINANCE ===
    'PSU Bank': [
        'BANKBARODA',
        'BANKINDIA',
        'CANBK',
        'INDIANB',
        'PNB',
        'SBIN',
        'UNIONBANK'
    ],
    'Private Bank': [
        'AXISBANK',
        'BANDHANBNK',
        'FEDERALBNK',
        'HDFCBANK',
        'ICICIBANK',
        'IDFCFIRSTB',
        'INDUSINDBK',
        'KOTAKBANK',
        'RBLBANK'
    ],
    'Bank Nifty': [
        'AUBANK',
        'AXISBANK',
        'BANKBARODA',
        'BANKINDIA',
        'CANBK',
        'FEDERALBNK',
        'HDFCBANK',
        'ICICIBANK',
        'IDFCFIRSTB',
        'INDIANB',
        'INDUSINDBK',
        'KOTAKBANK',
        'PNB',
        'SBIN'
    ],
    'Financial Services': [
        '360ONE',
        'ABCAPITAL',
        'ANGELONE',
        'AXISBANK',
        'BAJAJFINSV',
        'BAJFINANCE',
        'BSE',
        'CDSL',
        'CHOLAFIN',
        'HDFCAMC',
        'HDFCBANK',
        'HDFCLIFE',
        'HUDCO',
        'ICICIBANK',
        'ICICIGI',
        'ICICIPRULI',
        'IIFL',
        'IRFC',
        'JIOFIN',
        'KOTAKBANK',
        'LICHSGFIN',
        'LICI',
        'LTF',
        'MANAPPURAM',
        'MFSL',
        'MUTHOOTFIN',
        'NUVAMA',
        'PAYTM',
        'PFC',
        'PNBHOUSING',
        'POLICYBZR',
        'RECLTD',
        'SAMMAANCAP',
        'SBICARD',
        'SBILIFE',
        'SBIN',
        'SHRIRAMFIN'
    ],

    // === CORE SECTORS ===
    'Auto': [
        'ASHOKLEY',
        'BHARATFORG',
        'BOSCHLTD',
        'EICHERMOT',
        'EXIDEIND',
        'HAL',
        'HEROMOTOCO',
        'M%26M',
        'MARUTI',
        'MOTHERSON',
        'SONACOMS',
        'TIINDIA',
        'TITAGARH',
        'TMPV',
        'TVSMOTOR',
        'UNOMINDA'
    ],
    'Metal': [
        'ADANIENT',
        'APLAPOLLO',
        'HINDALCO',
        'HINDZINC',
        'JINDALSTEL',
        'JSWSTEEL',
        'NATIONALUM',
        'NMDC',
        'SAIL',
        'TATASTEEL',
        'VEDL'
    ],
    'Energy': [
        'ADANIENSOL',
        'ADANIGREEN',
        'BDL',
        'BHEL',
        'BLUESTARCO',
        'BPCL',
        'CGPOWER',
        'COALINDIA',
        'GMRAIRPORT',
        'HINDPETRO',
        'IEX',
        'IGL',
        'INOXWIND',
        'IOC',
        'IREDA',
        'JSWENERGY',
        'MAZDOCK',
        'NHPC',
        'NTPC',
        'OIL',
        'ONGC',
        'PETRONET',
        'POWERGRID',
        'POWERINDIA',
        'RELIANCE',
        'SOLARINDS',
        'SUZLON',
        'TATAPOWER',
        'TORNTPOWER'
    ],
    'Oil & Gas': [
        'BPCL',
        'GAIL',
        'HINDPETRO',
        'IOC',
        'OIL',
        'ONGC',
        'PETRONET',
        'RELIANCE'
    ],

    // === CONSUMER & SERVICES ===
    'FMCG': [
        'BRITANNIA',
        'COLPAL',
        'DABUR',
        'DMART',
        'ETERNAL',
        'GODREJCP',
        'HINDUNILVR',
        'ITC',
        'MARICO',
        'NESTLEIND',
        'NYKAA',
        'PATANJALI',
        'SUPREMEIND',
        'TATACONSUM',
        'UBL',
        'UNITDSPR',
        'VBL'
    ],
    'Consumer Durables': [
        'AMBER',
        'BATAINDIA',
        'BLUESTARCO',
        'CROMPTON',
        'DIXON',
        'HAVELLS',
        'KALYANKJIL',
        'PGEL',
        'TITAN',
        'VOLTAS'
    ],
    'Consumption': [
        'AMBUJACEM',
        'APOLLOHOSP',
        'ASIANPAINT',
        'BAJAJ-AUTO',
        'BHARTIARTL',
        'BRITANNIA',
        'DALBHARAT',
        'DELHIVERY',
        'DIXON',
        'DLF',
        'DMART',
        'EICHERMOT',
        'ETERNAL',
        'GODREJCP',
        'GRASIM',
        'HAVELLS',
        'HEROMOTOCO',
        'HINDUNILVR',
        'INDHOTEL',
        'INDIGO',
        'ITC',
        'KEI',
        'M%26M',
        'MARUTI',
        'MAXHEALTH',
        'NAUKRI',
        'NESTLEIND',
        'PIDILITIND',
        'TATACONSUM',
        'TATAPOWER',
        'TITAN',
        'TRENT',
        'TVSMOTOR',
        'ULTRACEMCO',
        'UNITDSPR',
        'VBL'
    ],
    'Realty': [
        'DLF',
        'GODREJPROP',
        'INDUSTOWER',
        'LODHA',
        'LT',
        'NBCC',
        'NCC',
        'OBEROIRLTY',
        'PHOENIXLTD',
        'PRESTIGE',
        'SIEMENS'
    ],
    'Pharma': [
        'ALKEM',
        'APOLLOHOSP',
        'AUROPHARMA',
        'BIOCON',
        'CIPLA',
        'DIVISLAB',
        'DRREDDY',
        'FORTIS',
        'GLENMARK',
        'LAURUSLABS',
        'LUPIN',
        'MANKIND',
        'MAXHEALTH',
        'PPLPHARMA',
        'SUNPHARMA',
        'SYNGENE',
        'TORNTPHARM',
        'ZYDUSLIFE'
    ],

    // === TECHNOLOGY ===
    'IT': [
        'ABB',
        'CAMS',
        'COFORGE',
        'CYIENT',
        'HCLTECH',
        'INFY',
        'KAYNES',
        'KFINTECH',
        'KPITTECH',
        'LTIM',
        'MPHASIS',
        'OFSS',
        'PERSISTENT',
        'TATAELXSI',
        'TATATECH',
        'TCS',
        'TECHM',
        'WIPRO'
    ],

    // === INDICES / BROAD MARKET ===
    'Sensex': [
        'ADANIPORT',
        'ASIANPAINT',
        'AXISBANK',
        'BAJAJFINSV',
        'BAJFINANCE',
        'BHARTIARTL',
        'ETERNAL',
        'HCLTECH',
        'HDFCBANK',
        'HINDUNILVR',
        'ICICIBANK',
        'INDUSINDBK',
        'INFY',
        'ITC',
        'KOTAKBANK',
        'LT',
        'M%26M',
        'MARUTI',
        'NESTLEIND',
        'NTPC',
        'POWERGRID',
        'RELIANCE',
        'SBIN',
        'SUNPHARMA',
        'TATASTEEL',
        'TCS',
        'TECHM',
        'TITAN',
        'TMPV',
        'ULTRACEMCO'
    ],
    'Nifty MidSelect': [
        'ASHOKLEY',
        'ASTRAL',
        'AUBANK',
        'AUROPHARMA',
        'BEL',
        'BHARATFORG',
        'COFORGE',
        'CONCOR',
        'CUMMINSIND',
        'FEDERALBNK',
        'GODREJPROP',
        'HDFCAMC',
        'HEROMOTOCO',
        'HINDPETRO',
        'IDFCFIRSTB',
        'INDHOTEL',
        'JUBLFOOD',
        'LUPIN',
        'MPHASIS',
        'MUTHOOTFIN',
        'PAGEIND',
        'PERSISTENT',
        'PIIND',
        'POLYCAB',
        'RVNL',
        'UPL',
        'VOLTAS'
    ]
}

/**
 * Get stock symbols for a given sector
 */
export function getStocksForSector(sectorName: string): string[] {
    return SECTOR_STOCKS[sectorName] || []
}

/**
 * Check if a sector has stock mappings
 */
export function hasSectorStocks(sectorName: string): boolean {
    return sectorName in SECTOR_STOCKS && SECTOR_STOCKS[sectorName].length > 0
}
